language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7

env:
  - DB=mysql
  - DB=postgres
  - DB=sqlite

gemfile: Gemfile.ci

# Only run a cross-section of 4 builds.
matrix:
  exclude:
    - rvm: 1.8.7
      env: DB=postgres
      gemfile: Gemfile.ci
    - rvm: 1.8.7
      env: DB=sqlite
      gemfile: Gemfile.ci
    - rvm: 1.9.2
      env: DB=sqlite
      gemfile: Gemfile.ci
    - rvm: 1.9.3
      env: DB=sqlite
      gemfile: Gemfile.ci
    - rvm: 1.9.3
      env: DB=mysql
      gemfile: Gemfile.ci

bundler_args: --path=vendor/bundle --without heroku

before_script:
  - sh -c "cp config/database.$DB.yml config/database.yml"
  - sh -c "if [ \"$DB\" = 'postgres' ]; then psql -c 'create database fat_free_crm_test;' -U postgres; fi"
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql -e 'create database fat_free_crm_test;'; fi"
  - "export DISPLAY=:99"
  - "sh -e /etc/init.d/xvfb start"

# Run specs & acceptance tests, and ensure that assets can compile without errors
script: "bundle exec rake && RAILS_ENV=production bundle exec rake assets:precompile:primary"

# To stop Travis from running tests for a new commit,
# add the following to your commit message: [ci skip]
# You should add this when you edit documentation or comments, etc.

