rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7

env:
  - DB=mysql
  - DB=postgres
  - DB=sqlite

# Only run a cross-section of 4 builds.
matrix:
  exclude:
    - rvm: 1.8.7
      env: DB=postgres
    - rvm: 1.8.7
      env: DB=mysql
    - rvm: 1.9.2
      env: DB=sqlite
    - rvm: 1.9.3
      env: DB=sqlite
    - rvm: 1.9.3
      env: DB=mysql


# Only build master branch
branches:
  only:
    - master

bundler_args: --gemfile=Gemfile.ci --path=vendor/bundle --without heroku development

before_install: gem install bundler --pre

before_script:
  - sh -c "if [ \"$DB\" = 'postgres' ]; then psql -c 'create database fat_free_crm_test;' -U postgres; fi"
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql -e 'create database fat_free_crm_test;'; fi"

# Run RSpec tests and ensure that assets can compile without errors
script: "bundle exec rake && bundle exec rake assets:precompile RAILS_ENV=production"


# To stop Travis from running tests for a new commit,
# add the following to your commit message: [ci skip]
# You should add this when you edit documentation or comments, etc.

