# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
# Fat Free CRM settings are stored in three places, and are loaded in the following order:
#
# 1) config/settings.default.yml
# 2) config/settings.yml  (if exists)
# 3) 'settings' table in database  (if exists)
#
# Any settings in `config/settings.yml` will override those in
# `config/settings.default.yml`, and settings in the database table have the highest priority.
#
# This settings arrangement offers a lot of flexibility:
#
# * Developers can add new settings to the application with default values,
#   without requiring the user to manually update setting files or run tasks.
# * No manual configuration is required to start the application after installation
# * IT administrators can change the default configuration by adding 'settings.yml'
#   to their git repo, or by running SQL that updates the 'settings' table in the database.
# * Admin users can change settings via the admin interface, without needing to edit YAML files.
#
# PLEASE DO NOT EDIT THE SETTINGS IN THIS FILE.
# COPY THE SETTINGS THAT YOU WANT TO OVERRIDE INTO `config/settings.yml`
#
#------------------------------------------------------------------------------


# Host
#------------------------------------------------------------------------------
# Host for URLs when action mailer generates emails.
#
# When sending email, you will need to set the host name so that the mailer can
# generate urls inside emails that point back to your site. Unlike controllers
# from Action Pack, the mailer instance doesn’t have any context about the
# incoming request, so you’ll need to provide all of the details needed to
# generate a URL.
#
# :host: "www.example.com"
#
:host: ""


# Base URL
#------------------------------------------------------------------------------
# Leave base_url blank if Fat Free CRM has been deployed in root URL, otherwise
# specify subdirectory. For example, when deployed to:
#
# http://www.domain.com       => :base_url: ""       # (leave blank)
# http://crm.domain.com       => :base_url: ""       # (leave blank)
# http://www.domain.com/crm   => :base_url: "/crm"   # (without trailing slash)
# http://www.domain.com/a/crm => :base_url: "/a/crm" # (without trailing slash)
#
:base_url: ""


# Locale
#------------------------------------------------------------------------------
# Default locale is American English.
#
:locale: "en-US"


# Settings for outgoing email (SMTP)
# Uncomment to set up for your specific mailer
#------------------------------------------------------------------------------
#:smtp:
  #:address                    : ""        # e.g. smtp.gmail.com
  #:from                       : ""        # e.g. no-reply@your-domain.com
  #:enable_starttls_auto       : true
  #:port                       : "587"
  #:authentication             : :plain
  #:user_name                  : ""
  #:password                   : ""

# Settings for the Email dropbox (IMAP)
# - Connection settings for the IMAP account, server and folders.
#------------------------------------------------------------------------------
:email_dropbox:
  :server                     : ""        # IMAP server name.
  :port                       : ""        # IMAP server port number.
  :ssl                        : ""        # True for secure IMAP connection, false othewise.
  :address                    : ""        # Dropbox email address.
  :user                       : ""        # User to login to the IMAP server.
  :password                   : ""        # Password to login to the IMAP server.
  :scan_folder                : ""        # Folder to scan for dropbox messages.
  :attach_to_account          : ""        # Attach emails to contact's account, if any.
                                          # (The rule above also applies to opportunities.)
#  :address_aliases:                      # Optional: List any aliases that you also want to
#    - example_alias@example.com          #           ignore when scanning recipients
#  :move_to_folder            : ""        # Optional: folder to move processed messages to.
#  :move_invalid_to_folder    : ""        # Optional: folder to move invalid messages to.



# Settings for 'Reply via email' inbox (IMAP)
#------------------------------------------------------------------------------
:email_comment_replies:
  :server                     : ""        # IMAP server name.
  :port                       : ""        # IMAP server port number.
  :ssl                        : ""        # True for secure IMAP connection, false othewise.
  :address                    : ""        # Comment reply email address.
  :user                       : ""        # User to login to the IMAP server.
  :password                   : ""        # Password to login to the IMAP server.
  :scan_folder                : ""        # Folder to scan for comment replies.
#  :move_to_folder            : ""        # Optional: folder to move processed messages to.
#  :move_invalid_to_folder    : ""        # Optional: folder to move invalid messages to.


# Individual locales per user
#------------------------------------------------------------------------------
# To enable language selection in User/Profile set the following option to true.
# By default, individual users can't pick their own locale and are presented
# with the default locale.
#
:per_user_locale: false


# Default records permissions
#------------------------------------------------------------------------------
# Set the defaults permission for new records. Possible values are:
#   Private -- private access, only for the creator of the record.
#   Public  -- public access, share with everyone. This is the default.
#   Shared  -- shared with selected accounts, should be selected by the user.
#
:default_access: "Public"


# User Signup
#------------------------------------------------------------------------------
# The following setting controls user signup. Possible values are:
#   :allowed        -- users can sign up and use the system once they have registered.
#   :not_allowed    -- users can only be added by system administrator. This is the default.
#   :needs_approval -- users can sign up but must be approved before they can use the system.
#
:user_signup: :not_allowed


# Address format
#------------------------------------------------------------------------------
# Sets the address format for Accounts, Contacts, and Leads.
#   true  -- use separate street1, street2, city, state, zipcode, and country field.  (default)
#   false -- use single text area field to enter the entire address.
#
:compound_address: true


# Dropdown calendar format
#------------------------------------------------------------------------------
# The following setting controls whether to show time in dropdown calendar
# when scheduling a task for specific date.
#   true  -- allow selecting date and time.  (default)
#   false -- allow selecting date only.
#
:task_calendar_with_time: true


# Enable/disable first/last name validations on Leads and Contacts
#------------------------------------------------------------------------------
#
:require_first_names: true
:require_last_names:  true

# Enable/disable name validation on Accounts
:require_unique_account_names: true

# Show comments on dashboard
:comments_visible_on_dashboard: false

# Background information
#------------------------------------------------------------------------------
# Specify model names that should have background information displayed.
# This field can be used when importing records from legacy databases,
# to display the 'background' of where they came from.
#
# Select any combination from the following list.
#
#   :background_info:
#     - :account
#     - :campaign
#     - :contact
#     - :lead
#     - :opportunity
#     - :task
#
# By default, no background information is shown.
#
:background_info: []

# Priority countries
#------------------------------------------------------------------------------
# Specify which countries (if any) should appear at the top of country pickers
# priority_countries:
#  - AU
#  - BF

# Main and Admin Tabs
#------------------------------------------------------------------------------
:tabs:
- :active: true
  :text: :tab_dashboard
  :icon: :fa-dashboard
  :url:
    :controller: home
- :active: false
  :text: :tab_tasks
  :icon: :fa-check-square-o
  :url:
    :controller: tasks
- :active: false
  :text: :tab_campaigns
  :icon: :fa-bar-chart-o
  :url:
    :controller: campaigns
- :active: false
  :text: :tab_leads
  :icon: :fa-tasks
  :url:
    :controller: leads
- :active: false
  :text: :tab_accounts
  :icon: :fa-users
  :url:
    :controller: accounts
- :active: false
  :text: :tab_contacts
  :icon: :fa-user
  :url:
    :controller: contacts
- :active: false
  :text: :tab_opportunities
  :icon: :fa-money
  :url:
    :controller: opportunities
- :active: false
  :text: :tab_team
  :icon: :fa-globe
  :url:
    :controller: users
    :action: opportunities_overview

:admin_tabs:
- :active: true
  :text: :admin_tab_users
  :icon: :fa-user
  :url:
    :controller: admin/users
- :active: true
  :text: :admin_tab_groups
  :icon: :fa-users
  :url:
    :controller: admin/groups
- :active: false
  :text: :admin_tab_fields
  :icon: :fa-list-alt
  :url:
    :controller: admin/fields
- :active: false
  :text: :admin_tab_tags
  :icon: :fa-tags
  :url:
    :controller: admin/tags
#- :active: false
#  :text: :admin_tab_settings
#  :icon: :fa-cogs
#  :url:
#    :controller: admin/settings
#- :active: false
#  :text: :admin_tab_plugins
#  :icon: :fa-plus-circle
#  :url:
#    :controller: admin/plugins

# Account Category. To add custom account type use string value, for example:
#
# account_category:
#   - "Custom"
#
#------------------------------------------------------------------------------
account_category:
  - :affiliate
  - :competitor
  - :customer
  - :partner
  - :reseller
  - :vendor

# Campaign Status. To add custom status use string value, for example:
#
# campaign_status:
#   - "Custom"
#
#------------------------------------------------------------------------------
campaign_status:
  - :planned
  - :started
  - :completed
  - :on_hold
  - :called_off

# Lead Status and Source.
#------------------------------------------------------------------------------
lead_status:
  - :new
  - :contacted
  - :converted
  - :rejected

lead_source:
  - :campaign
  - :cold_call
  - :conference
  - :online
  - :referral
  - :self
  - :web
  - :word_of_mouth
  - :other

# Opportunity Stage.
#------------------------------------------------------------------------------
opportunity_default_stage: :prospecting
opportunity_stage:
  - :prospecting
  - :analysis
  - :presentation
  - :proposal
  - :negotiation
  - :final_review
  - :won
  - :lost

# Task Category, Due Date, and Completed Date.
#------------------------------------------------------------------------------
task_category:
  - :call
  - :email
  - :follow_up
  - :lunch
  - :meeting
  - :money
  - :presentation
  - :trip

task_bucket:
  - :overdue
  - :due_asap
  - :due_today
  - :due_tomorrow
  - :due_this_week
  - :due_next_week
  - :due_later

task_completed:
  - :completed_today
  - :completed_yesterday
  - :completed_last_week
  - :completed_this_month
  - :completed_last_month
