# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Rspec

on:
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7'] # , '2.7', '3.0'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@72d59482210349c1114eca714b6c5df19fbbec34
      with:
        ruby-version: ${{ matrix.ruby-version }}
        # bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Install dependencies
      run: bundle install
    - name: Prepare DB
      run: DB=sqlite RAILS_ENV=test bundle exec rake spec:preparedb
    - name: Run model tests
      run: DB=sqlite bundle exec rake spec:models
    - name: Run controller tests
      run: bundle exec rake spec:controllers
    - name: Run view tests
      run: bundle exec rake spec:views
    - name: Run helper tests
      run: bundle exec rake spec:helpers
    - name: Run route tests
      run: bundle exec rake spec:routing
    - name: Run mailer tests
      run: bundle exec rake spec:mailers
    - name: Run lib tests
      run: bundle exec rake spec:lib
